
export enum categories{
    ELECTRICITY = "ELECTRICITY",
    GAMING = "GAMING",
    MOBILE = "MOBILE",
    FOOD = "FOOD",
    HOME = "HOME",
    FASHION = "FASHION",
    COSMETICS = "COSMETICS",
    PHARMACY = "PHARMACY",
    PETS = "PETS",
    TOURISM = "TOURISM",
    OUTDOOR = "OUTDOOR",
    RESTAURANTS = "RESTAURTS",    
}